### ISSUE TITLE
Custom segments not working

### ISSUE THREAD

**Issue by magnusriga** [Rolv-Apneseth/starship.yazi#12]
Thanks for an excellent plugin.

One issue I encountered:

Custom segments do not display correctly. For instance:

This works well on the normal command line:

```toml
[custom.directory-with-git]
command = 'echo ${${PWD##*/}:-/}' # shows output of command
# format = '[$output](bg:red)[](fg:red)'
format = '[ $output ](bold bg:red fg:#000000)[](fg:red bg:yellow)'
when = """
if git rev-parse --git-dir > /dev/null 2>&1; then
  return 0
else
  return 1
fi
"""

[custom.directory-without-git]
command = 'echo ${${PWD##*/}:-/}' # shows output of command
format = '[ $output ](bold bg:red fg:#000000)[ ](fg:red)'
when = """
if git rev-parse --git-dir > /dev/null 2>&1; then
  return 1
else
  return 0
fi
"""

```

Inside yazi, however, nothing is displayed.

Screenshot on terminal:

![image](https://github.com/user-attachments/assets/99cfde33-562d-4554-8508-5f269b857cce)

Screenshot inside yazi:

![image](https://github.com/user-attachments/assets/48ea6a4b-0df3-4a29-9318-b921b45d04ea)

Any idea how I can fix that?

Thanks again.

**Comment by Rolv-Apneseth** [comment]
Looks like this is caused by setting `STARSHIP_SHELL=""`. A potential fix is just setting the following in both custom blocks:

```toml
shell = ["zsh"]
```

For some reason only the `zsh` option seems to be working for me in both `bash` and `zsh` shells, even with changing the command to `'echo "$(basename "$PWD")"'`. Tested with `STARSHIP_SHELL="" starship prompt`.

Not sure I can do anything on this plugin's end about this specific issue anyway so hopefully that solution is good enough for you.

**Comment by magnusriga** [comment]
Fantastic, that works. Thank you.

**Comment by Rolv-Apneseth** [comment]
No problem
